### ISSUE TITLE
The URL param to access to a specific location course dates is not working

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/website-v2#318]
When I access to [https://4geeksacademy.co/es/calendario?l=madrid-spain](https://4geeksacademy.co/es/calendario?l=madrid-spain), websites shows all Locations. When a location is promoting its courses through an URL, that could be an extra, unnecessary, step for potential clients.

**Comment by alesanchezr** [comment]
This is true @plucodev 

The way to fix this is using `?location=madrid-spain` instead of `?l=madrid-spain`.

When u use the `location` param on the querystring the session will initialize with `session.location` being an object that contains all the information about madrid.

In you filters, you need to mark as default (selected) the location on the `session.location` and that will fix it.

**Comment by alesanchezr** [comment]
Also, we need to parse the `window.location.hash` and get the `location` parameter.

For example: `https://4geeksacademy.co?location=madrid-spain#location=downtown-miami`
